# Henter data

Kode under er hentet fra chatGPT for å få et datasett fra enova.

In [7]:
import os
import requests
import pandas as pd
from pathlib import Path
KEY = "a0730ee88d3d48d59dd0d8cb06268c64"

# --- Sett inn din personlige API-nøkkel her ---
API_KEY = KEY

def hent_bankfile_url(year: int) -> str:
    api_url = f"https://api.data.enova.no/ems/offentlige-data/v1/Fil/{year}"
    r = requests.get(api_url, headers={"x-api-key": API_KEY}, timeout=60)
    r.raise_for_status()
    j = r.json()
    url = j["bankFileUrl"]  # <- dette er selve CSV-filen (midlertidig lenke)
    assert url.endswith(".csv") or ".csv?" in url
    return url

def last_ned_csv(url: str, dest_path: str, chunk=1024*1024):
    with requests.get(url, stream=True, timeout=600) as r:
        r.raise_for_status()
        with open(dest_path, "wb") as f:
            for b in r.iter_content(chunk_size=chunk):
                if b:
                    f.write(b)

def les_enova_år(year: int) -> pd.DataFrame:
    url = hent_bankfile_url(year)
    Path("data").mkdir(exist_ok=True)
    local = f"data/enova_{year}.csv"
    last_ned_csv(url, local)
    df = pd.read_csv(local, sep=",", low_memory=False)
    df["kildeår"] = year
    return df

In [8]:
# Etter at du har hentet alle år:
years = [2020, 2021, 2022, 2023, 2024]
alle = []

for y in years:
    try:
        print("Henter", y)
        alle.append(les_enova_år(y))
    except Exception as e:
        print("Feil for", y, "->", e)

df = pd.concat(alle, ignore_index=True)
print("Totalt antall rader:", len(df))

# --- 💾 Lagre som lokal CSV for videre bruk ---
df.to_csv("energi_data_2020_2024.csv", index=False)
print("Data lagret som energi_data_2020_2024.csv ✅")

Henter 2020
Henter 2021
Henter 2022
Henter 2023
Henter 2024
Totalt antall rader: 661472
Data lagret som energi_data_2020_2024.csv ✅

In [10]:
df.head(3)

,Knr,Gnr,Bnr,Snr,Fnr,Andelsnummer,Bygningsnummer,GateAdresse,Postnummer,Poststed,...,Oppvarmingskarakter,Utstedelsesdato,TypeRegistrering,Attestnummer,BeregnetLevertEnergiTotaltkWhm2,BeregnetFossilandel,Materialvalg,HarEnergiVurdering,EnergiVurderingDato,kildeår
0,4601.0,114,226,1,NaN,NaN,23636719,Skagevegen 73 A,5258.0,BLOMSTERDALEN,...,Yellow,2020-12-31T20:36:04.0000000,Simple,A2020-1211914,134.95,NaN,Tre,False,NaN,2020
1,301.0,224,68,NaN,NaN,NaN,NaN,Hans Nielsen Hauges gate 12,481.0,0481,...,Green,2020-12-31T16:33:21.0000000,Simple,A2020-1211913,403.62,NaN,Mur/tegl,False,NaN,2020
2,301.0,168,92,16,NaN,NaN,81074275,Skullerudveien 67,1188.0,OSLO,...,Red,2020-12-31T16:06:30.0000000,Simple,A2020-1211912,160.38,NaN,Betong,False,NaN,2020

Litt småfiks for å gjøre datasettet lettere å bruke

In [13]:
df.columns = (
    df.columns
    .str.strip()             
    .str.replace(" ", "_") 
    .str.replace("/", "_")  
    .str.replace("å", "a")
    .str.replace("æ", "ae")
    .str.replace("ø", "o")
    .str.lower()
)

In [14]:
df.head(3)

,knr,gnr,bnr,snr,fnr,andelsnummer,bygningsnummer,gateadresse,postnummer,poststed,...,oppvarmingskarakter,utstedelsesdato,typeregistrering,attestnummer,beregnetlevertenergitotaltkwhm2,beregnetfossilandel,materialvalg,harenergivurdering,energivurderingdato,kildear
0,4601.0,114,226,1,NaN,NaN,23636719,Skagevegen 73 A,5258.0,BLOMSTERDALEN,...,Yellow,2020-12-31T20:36:04.0000000,Simple,A2020-1211914,134.95,NaN,Tre,False,NaN,2020
1,301.0,224,68,NaN,NaN,NaN,NaN,Hans Nielsen Hauges gate 12,481.0,0481,...,Green,2020-12-31T16:33:21.0000000,Simple,A2020-1211913,403.62,NaN,Mur/tegl,False,NaN,2020
2,301.0,168,92,16,NaN,NaN,81074275,Skullerudveien 67,1188.0,OSLO,...,Red,2020-12-31T16:06:30.0000000,Simple,A2020-1211912,160.38,NaN,Betong,False,NaN,2020

In [15]:
df.to_csv("energimerke_rådata.csv", index=False)